services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.3"
        COMPOSER_VERSION: "2.7.9"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: vendor
        target: /app/vendor

volumes:
  vendor:
