services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: "8.3"
        COMPOSER_VERSION: "2.7.9"
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: vendor
        target: /app/vendor

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: docker/nginx/conf.d/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - app

volumes:
  vendor:
